title: Dave13h.GitHub.io
description: 
google_analytics: 
show_downloads: false
theme: jekyll-theme-slate
permalink: /:year/:month/:day/:title

gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-seo-tag
